language: go

go:
  - 1.x

script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build -t locnh/fxbot .

deploy:
  - provider: script
    script: bash scripts/docker-push.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|devel)$